// Retimes all seed days so Day #1 lands on the launch date.
// Usage: node scripts/redate-seed.js [YYYY-MM-DD]  (default: today, UTC)
const fs = require("fs");
const path = require("path");
const DATA = path.join(__dirname, "..", "data");
const start = process.argv[2] || new Date().toISOString().slice(0, 10);
if (!/^\d{4}-\d{2}-\d{2}$/.test(start)) throw new Error("bad date: " + start);

const days = JSON.parse(fs.readFileSync(path.join(DATA, "seed-days.json")));
const t0 = new Date(start + "T12:00:00Z").getTime();
days.forEach((d, i) => { d.date = new Date(t0 + i * 86400000).toISOString().slice(0, 10); });
fs.writeFileSync(path.join(DATA, "seed-days.json"), JSON.stringify(days, null, 2));

const esc = (s) => s.replace(/'/g, "''");
let sql = "-- Generated by content-pipeline. Real pre-2023 human texts + matched AI twins + celebrity days.\n";
sql += "INSERT OR REPLACE INTO days (date, day_number, cards_json) VALUES\n";
sql += days.map((d) => `  ('${d.date}', ${d.day_number}, '${esc(JSON.stringify(d.cards))}')`).join(",\n") + ";\n";
sql += `DELETE FROM days WHERE date NOT IN (${days.map((d) => `'${d.date}'`).join(",")});\n`;
fs.writeFileSync(path.join(__dirname, "..", "seed.sql"), sql);
console.log(`seed retimed: day #1 = ${days[0].date} .. day #${days.length} = ${days[days.length - 1].date}`);
